server:
  port: 8080

spring:
  h2:
    console:
      enabled: true



  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.H2Dialect

logging.level:
  org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true

cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET}
      region: ${AWS_REGION}
      stack:
        auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}